name: CI
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  test:
    strategy:
      matrix:
        pg: [13, 14]
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Test on PostgreSQL ${{ matrix.pg }}
        run: pg-build-test
